### ISSUE TITLE
download openvino_toolkit fail when run environment_setup_binary.sh

### ISSUE THREAD

**Issue by yechun1** [intel/ros2_openvino_toolkit#117]
$ wget -c http://registrationcenter-download.intel.com/akdlm/irc_nas/15512/l_openvino_toolkit_p_2019.1.144.tgz
--2019-09-11 13:47:33--  http://registrationcenter-download.intel.com/akdlm/irc_nas/15512/l_openvino_toolkit_p_2019.1.144.tgz
Resolving child-prc.intel.com (child-prc.intel.com)... 10.239.4.101
Connecting to child-prc.intel.com (child-prc.intel.com)|10.239.4.101|:913... connected.
Proxy request sent, awaiting response... 503 Service Unavailable
2019-09-11 13:47:33 ERROR 503: Service Unavailable.

**Comment by LewisLiuPub** [comment]
No plan to fix that kind of network connection issues...
