### ISSUE TITLE
timestamp in output topic is inconsistent with the corresponding input topic

### ISSUE THREAD

**Issue by xhuan28** [intel/ros2_openvino_toolkit#136]
I print some timestamps in [pipeline.cpp](https://github.com/intel/ros2_openvino_toolkit/blob/devel/dynamic_vino_lib/src/pipeline.cpp#L211) and find that the timestamp is inconsistent with the one for the frame being processed.
```
 auto test_t0 = rclcpp::Clock(RCL_ROS_TIME).now();
  std::unique_lock<std::mutex> lock(counter_mutex_);
  cv_.wait(lock, [self = this]() {return self->counter_ == 0;});
  
  auto headerr = getInputDevice()->getHeader();
  auto msg_time = rclcpp::Time(headerr.stamp);
  auto test_t1 = rclcpp::Clock(RCL_ROS_TIME).now();
  std::cout << "**************************" << std::endl;
  std::cout << "msg_time: " << msg_time.nanoseconds() << std::endl;
  std::cout << "test_t0: " << test_t0.nanoseconds() << std::endl;
  std::cout << "test_t1: " << test_t1.nanoseconds() << std::endl;
  std::cout << "t1-t0: " << (test_t1-test_t0).nanoseconds()*1e-6 << std::endl;
  std::cout << "msg duration: " << (test_t1 - msg_time).nanoseconds()*1e-6 << std::endl;
  std::cout << "**************************" << std::endl;
```
Output:

> [pipeline_with_params-1] **************************
[pipeline_with_params-1] msg_time: 1572420170529247967
[pipeline_with_params-1] test_t0: 1572420170502623887
[pipeline_with_params-1] test_t1: 1572420170547616668
[pipeline_with_params-1] t1-t0: 44.9928
[pipeline_with_params-1] msg duration: 18.3687
[pipeline_with_params-1] **************************

`test_t0` is even smaller than `msg_time`, which is abnormal. This issue may impact performance test.

**Comment by LewisLiuPub** [comment]
patch for this issue:
https://github.com/intel/ros2_openvino_toolkit/pull/137/commits/f772afe69123c98fd6cfc665c9ebea3360ef719c
