### ISSUE TITLE
error dynamic_vino_sample' not found

### ISSUE THREAD

**Issue by julian533** [intel/ros2_openvino_toolkit#183]
Hello, 
I have tried containerizing the application with Docker. When I use the following command inside the container:
 ```
ros2 launch dynamic_vino_sample pipeline_face_reidentification.launch.py
```
I get the below error message:
```
Package 'dynamic_vino_sample' not found: "package 'dynamic_vino_sample' not found, searching: ['/opt/ros/dashing']"
```
Any suggestions what I could change?

**Comment by surfertas** [comment]
Can you share the docker file?

**Comment by LewisLiuPub** [comment]
Will close the issue. Suppose the latest source code in branch master or ros2 has no such error.
Create a new one if you occur it again.
