### ISSUE TITLE
Unknown CMake command "ament_export_targets".

### ISSUE THREAD

**Issue by MrJohnRobert** [intel/ros2_openvino_toolkit#187]
Based on the guidance document BINARY_VERSION_README in ROS2_openvino_Toolkit, setup environment is ROS dashing and OpenVino 2020.3. I now have a question whether Ament compiling tools are required. According to the information, Presenting Ament is a previous generation of Colcon compiling tools. Since I can't configure Ament at the moment, how can I solve this problem:CMake Error at cmakelists. TXT :58 (ament_export_targets): Unknown CMake command "ament_export_targets".

**Comment by LewisLiuPub** [comment]
Hi, @MrJohnRobert , thanks for your reporting.
Currently OpenVINO 2020.3 and latest ROS2 version is not supported by this project, we are in progress to upgrade and support them.  I'll let your know once ready. Thank you for your further contribution.
