### ISSUE TITLE
Preferred version of Ubuntu

### ISSUE THREAD

**Issue by sapoluri** [intel/ros2_openvino_toolkit#198]
The ROS2 version I intend to use is Foxy. Foxy's preferred Ubuntu version is 20.04.

OpenVino 2021.1/2021.2 both support Ubuntu 20.04. Will ros2_openvino_toolkit work with OpenVino 2021.1/2021.2?

**Comment by LewisLiuPub** [comment]
yes, in progress.

**Comment by sapoluri** [comment]
Any estimate on when it might released?

**Comment by LewisLiuPub** [comment]
I am now in progress of porting this project to support Ubuntu 20.04.
Could you please let me know more about your use of this project, thus I can judge correctly and make a better development schedule for you? @sapoluri

**Comment by LewisLiuPub** [comment]
@sapoluri 
Ubuntu20.04 has been officially supported by now. please track the new branch: [dev-ov.2021.3](https://github.com/intel/ros2_openvino_toolkit/tree/dev-ov.2021.3)
