### ISSUE TITLE
Yolov3 support in Object detection

### ISSUE THREAD

**Issue by joelbudu** [intel/ros2_openvino_toolkit#199]
According to the documentation I can see SSD and Yolov2 models are supported. 
Does this library support also higher versions of yolo like v3 and also are there plans to support other popular object detection models like faster R-CNN?

**Comment by LewisLiuPub** [comment]
Currently, only yolov2 is supported.

There are some voluteers from ROS community also interested in yolo series models, I am sync'ing with them and calling on their contribution. Any idea/comment/effort is appreciated from any one here.

**Comment by LewisLiuPub** [comment]
yolov5 has been supported in branch master and branch ros2.
yolov3 is not in plan.

**Comment by joelbudu** [comment]
Thank you for working on this @LewisLiuPub
