### ISSUE TITLE
Parallel acceleration for detection models

### ISSUE THREAD

**Issue by joelbudu** [intel/ros2_openvino_toolkit#201]
@LewisLiuPub  is possible to get the functionality to have parallel execution for detection models as similar to this PR? - #143. Would be very useful to get faster speeds especially on the Movidius VPU

**Comment by LewisLiuPub** [comment]
Hi, @joelbudu 
Do you need to input multiple data from several cameras? or only use one camera but want to execute the inference by several Movidius VPUs in parallel?

**Comment by joelbudu** [comment]
@LewisLiuPub I would like to use one camera but execute the inference by several Movidius VPUs in parallel, please.

**Comment by LewisLiuPub** [comment]
@joelbudu Can you let me know more, which model(s) are you using in this case?

**Comment by joelbudu** [comment]
Object Detection -> YOLOV2
Object Segmentation -> MaskRCNN

**Comment by LewisLiuPub** [comment]
To update the status for multiple pipeline supporting and yolo/maskrcnn supporting:
- Yolov2 is deprecated. Instead, Yolov5 is supported. 
- instance segmentation (maskrcnn, deeplabv3) is supported on branch ros2 (enabled for ros2 foxy/galactic)

**Comment by joelbudu** [comment]
Thank you for working on this @LewisLiuPub
