### ISSUE TITLE
ROS2 on Windows Support?

### ISSUE THREAD

**Issue by RMichaelPickering** [intel/ros2_openvino_toolkit#205]
Is there any plan to support ROS2 on Windows? We've been using both OpenVINO and RealSense SDK on Windows for quite some time already! Of course, ROS2 has a big release due next month, and as far as I know ROS2 is well supported on Windows too!

**Comment by LewisLiuPub** [comment]
Thanks for your question.
Let me evaluate the possibility to find some extra effort to make it ready on Windows. Will make you posted once any results.

**Comment by LewisLiuPub** [comment]
Yes. Close this issue and keep the one newly created.
