### ISSUE TITLE
ROS2 Galactic Release?

### ISSUE THREAD

**Issue by sink0918** [intel/ros2_openvino_toolkit#213]
I'd like to know when ROS2 Galactic will be supported.

**Comment by LewisLiuPub** [comment]
yes, I am planning resources/bandwidth just now to make it happen, please expect its readiness in 1 or 2 months.

**Comment by LewisLiuPub** [comment]
@sink0918 I just merged code supporting Galactic to Branch master. You may have a check and let us know if any issue.
