### ISSUE TITLE
The links and images on document files are disconnected

### ISSUE THREAD

**Issue by dtoya** [intel/ros2_openvino_toolkit#217]
Hello,

The links and image files on the following pages are disconnected. Could you please correct the pages? 

https://github.com/intel/ros2_openvino_toolkit/blob/master/doc/tables_of_contents/Design_Architecture_and_logic_flow.md
https://github.com/intel/ros2_openvino_toolkit/blob/master/doc/tables_of_contents/supported_features/Supported_features.md
https://github.com/intel/ros2_openvino_toolkit/blob/master/doc/tables_of_contents/tutorials/configuration_file_customization.md
https://github.com/intel/ros2_openvino_toolkit/blob/master/doc/tables_of_contents/tutorials/Multiple_Pipelines.md

**Comment by LewisLiuPub** [comment]
Please refer [the doc](https://github.com/intel/ros2_openvino_toolkit/blob/master/doc/quick_start/getting_started_with_ros2_ov2.0.md) for getting start. Let us know if it is not enough.
