### ISSUE TITLE
Cmake Error at CMakeLists.txt InferenceEngineConfig not accepted. ROS Foxy

### ISSUE THREAD

**Issue by Kirpici** [intel/ros2_openvino_toolkit#226]
Colcon build fails for dynamic _vino_test and dynamic_vino_sample. Can not run the demos either. It says that there is no configuration file for package "InferenceEngine"

**Comment by LewisLiuPub** [comment]
Hi, @Kirpici  currently we updated the related Dockerfile, could you try to build ROS2_OpenVINO in a docker, by using the [Dockerfile](https://github.com/intel/ros2_openvino_toolkit/blob/master/docker/ros2_2021.4/ros2_galactic/Dockerfile)?

We are also update source code and document to fix the build errors.
