### ISSUE TITLE
DeeplabV3 Segmantic segmentation not running

### ISSUE THREAD

**Issue by joelbudu** [intel/ros2_openvino_toolkit#239]
I've tried to run the [steps for converting a deeplabV3 model](https://github.com/intel/ros2_openvino_toolkit/blob/master/doc/quick_start/getting_started_with_Dashing_Ubuntu18.04.md) and running this using the 
`ros2 launch dynamic_vino_sample pipeline_segmentation.launch.py
` example. 

Unfortunately I am unable to get an inference output from the model and the logs get stuck at this point below:

`input_names: 
[pipeline_with_params-1] [ INFO ] |    input-->mul_1/placeholder_port_1
[pipeline_with_params-1] [ INFO ] | output_names: 
[pipeline_with_params-1] [ INFO ] |    detection-->ArgMax/Squeeze
[pipeline_with_params-1] [ INFO ] |    masks-->ArgMax/Squeeze

[pipeline_with_params-1] [ DEBUG ] DEBUG: in Pipeline run process...
[pipeline_with_params-1] [ DEBUG ] DEBUG: Enqueue for detection: ObjectSegmentation
[pipeline_with_params-1] [ DEBUG ] first tensor4
[pipeline_with_params-1] [ DEBUG ] DEBUG: Submit Infer request for detection: ObjectSegmentation
[pipeline_with_params-1] [ DEBUG ] Async Inference started!
[pipeline_with_params-1] [ DEBUG ] DEBUG: align inference process, waiting until all inferences done!
[pipeline_with_params-1] [ DEBUG ] Hello callback ----> ObjectSegmentation
[pipeline_with_params-1] [ DEBUG ] Analyzing Detection results...`

Any assistance would be appreciated.

**Comment by LewisLiuPub** [comment]
Will close the issue. Suppose the latest source code in branch master or ros2 has no such error.
Create a new one if you occur it again.
