### ISSUE TITLE
Which branch with which OpenVINO version?

### ISSUE THREAD

**Issue by hcdiekmann** [intel/ros2_openvino_toolkit#254]
Which branch/ros distro to use with which version of openVINO? Is there some documentation on this?

**Comment by LewisLiuPub** [comment]
using branch **ros2** for the latest ros distros (foxy, galactic and humble) and the latest openVINO (v2022.2).
using branch *foxy** for ros foxy and openvino v2021.4LTS version.

Yes, we will provide documentation on this version matching info.

Thanks.
