### ISSUE TITLE
Unexpected removal of user space stuff

### ISSUE THREAD

**Issue by EwingKang** [intel/ros2_openvino_toolkit#80]
I'm very, very surprised that the script [environment_setup.sh](https://github.com/intel/ros2_openvino_toolkit/blob/master/script/environment_setup.sh#L75) ACTUALLY REMOVES everything without even a warning. I've paid a very high price of loosing everything in my _/ros2_ws_, which is my ROS2 equivalent of _/catkin_ws_ (since my ROS2 is installed by apt).
And its behavior of grabing the ROS2 Crystal source code and rebuild it from scratch, while there is a viable apt version which is far quicker, doesn't make too much sense to me.

IMHO, the default install configuration in [modules.conf](https://github.com/intel/ros2_openvino_toolkit/blob/master/script/modules.conf) should be set to not remove anything.
Documents suggesting to execute that pprticular bash such as BINARY_VERSION_README.md should add some warning text to it.

**Comment by LewisLiuPub** [comment]
Thank you very much for your contribution and comments. I realized that it is really bad no warning info before removing important collaterals.  the correspondent readme and script will be updated soon.
