### ISSUE TITLE
build failed when building dynamic_vino_lib

### ISSUE THREAD

**Issue by xhuan28** [intel/ros2_openvino_toolkit#88]
$colcon build --symlink-install

--- stderr: dynamic_vino_lib                           
CMake Error at CMakeLists.txt:68 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

make: *** [cmake_check_build_system] Error 1
---
Failed   <<< dynamic_vino_lib	[ Exited with code 2 ]

**Comment by xhuan28** [comment]
This issue is caused by not supporting 2019R1 release of OpenVINO toolkit

**Comment by LewisLiuPub** [comment]
Close, because it can't be reproduced in the latest version.

**Comment by portgasray** [comment]
#160

**Comment by portgasray** [comment]
> This issue is caused by not supporting 2019R1 release of OpenVINO toolkit

so, what's your suggestion?

I used your doc [OPEN_SOURCE_CODE_README](https://github.com/intel/ros2_openvino_toolkit/blob/master/doc/OPEN_SOURCE_CODE_README.md), and tried the following the step showing as the pic, it still happened like above!  Check my issue #160 

![ROS2_OpenVINO](https://user-images.githubusercontent.com/17681580/69399106-dbc18580-0d27-11ea-9d61-8aab59c6994a.png)
